package application;
import java.lang.reflect.Array;
import java.util.ArrayList;
/**
 *
 * @author Jazmin Roxana Arias Salazar
 */
public class T extends javax.swing.JFrame {
    
    private String[] letters = new String[]{"A","R","B","N","V","M"};
    private String[] combination = new String[4];
    private int attempts;
    
    public T() {
        initComponents();
        
        disableBtn();
        attempts = 8;
        attemptsAvailable.setText( String.valueOf(attempts) );
        generateRandomLetters();
    }
    
    private void generateRandomLetters(){
        int range = 6;
      
       for(int i = 0; i <= 3; i++ ){
           int rand = ( int )( Math.random() * range );
           System.out.println(rand);
           combination[i] = letters[rand];
       }
    }
     
    private void turnIntoArray(){
        String tried = attempt.getText();
        char[] x = new char[4];
        
        if(tried.length() != 4){
            erroMsg();
        }else{
            for( int i = 0; i < tried.length(); i++ ){
                x[i] = tried.charAt(i);
            }
            validateLetters(x);
        }
    }
    
    private void validateLetters(char[] x){
        int total = compare(x);
        
        if( total != 0 && total < 4){
            successTotalMsg(total);
            int exist = exist(x);
            
            if(exist != 0 && exist < 4){
                successPartialMsg(exist);
            }
            
            subtractAttempts();
            
        }else if(total == 4){
            
            successTotalMsg(total);
            disableBtn();
            btnStartGame.setEnabled(true);
            result.setText("Usted ganó");
            result2.setText("");
            generateRandomLetters();
        }
    }
    
    private int exist(char[] x){
        int cont = 0;
         
        for(int i = 0; i < x.length; i++){ 
            for ( String letter : combination) {
                if (letter.equals( String.valueOf(x[i]) )) {
                    cont += 1;
                }   
            }
        }
        return cont;
    }
    
    private void successPartialMsg(int num){
       result2.setText("Aciertos parciales: " + num);
    }
    
    private void successTotalMsg(int num){
        result.setText("Aciertos totales: " + num);
    }
    
    private void disableBtn(){
        attempt.setEnabled(false);
        btnSubmit.setEnabled(false);
    }
    
    private void erroMsg(){
        if(attempts != 0){
            result.setText("Intentelo de nuevo");
            subtractAttempts();
        }else{
            result.setText("Game Over");
            btnStartGame.setEnabled(true);
            disableBtn();
        }
    }
    
    private void subtractAttempts(){
        if(attempts != 0){
            attempts -= 1;
            attemptsAvailable.setText(String.valueOf(attempts));
        }else{
            erroMsg();
        }
    }
    
    private int compare(char[] x){
        int cont = 0;
        
        for(int i = 0; i < combination.length; i++){
            if(combination[i].equals(String.valueOf(x[i]))){
                cont += 1 ;
            }
        }
        return cont;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStartGame = new javax.swing.JButton();
        attempt = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        result = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        attemptsAvailable = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        result2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnStartGame.setText("Iniciar juego");
        btnStartGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStartGameMouseClicked(evt);
            }
        });

        attempt.setToolTipText("");

        btnSubmit.setText("Confirmar");
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmitMouseClicked(evt);
            }
        });

        jLabel1.setText("Intentos disponibles:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStartGame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(attemptsAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(attempt, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(btnSubmit)
                        .addGap(31, 31, 31)
                        .addComponent(result2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStartGame)
                    .addComponent(jLabel1)
                    .addComponent(attemptsAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(attempt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSubmit)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(result2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseClicked
        turnIntoArray();

    }//GEN-LAST:event_btnSubmitMouseClicked

    private void btnStartGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartGameMouseClicked
        btnStartGame.setEnabled(false);
        attempt.setEnabled(true);
        btnSubmit.setEnabled(true);
    }//GEN-LAST:event_btnStartGameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(T.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(T.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(T.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(T.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new T().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField attempt;
    private javax.swing.JLabel attemptsAvailable;
    private javax.swing.JButton btnStartGame;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel result;
    private javax.swing.JLabel result2;
    // End of variables declaration//GEN-END:variables
}
