package com.cenfotec.componentes.control;

import java.lang.reflect.Array;
import java.util.ArrayList;

/**
 *
 * @author Jazmin Arias
 */
public class ComponentePrincipal extends javax.swing.JPanel {

    private String[] letters = new String[]{"A","R","B","N","V","M"};
    private String[] combination = new String[4];
    int attempts;
    
    
    public ComponentePrincipal() {
                 initComponents();
        
        disableBtn();
        attempts = 8;
        attemptsAvailable.setText( String.valueOf(attempts) );
        generateRandomLetters();
    }
    
    private void generateRandomLetters(){
        int range = 6;
      
       for(int i = 0; i <= 3; i++ ){
           int rand = ( int )( Math.random() * range );
           System.out.println(rand);
           combination[i] = letters[rand];
       }
    }
     
    private void turnIntoArray(){
        String tried = attempt.getText();
        char[] x = new char[4];
        
        if(tried.length() != 4){
            erroMsg();
        }else{
            for( int i = 0; i < tried.length(); i++ ){
                x[i] = tried.charAt(i);
            }
            validateLetters(x);
        }
    }
    
    private void validateLetters(char[] x){
        int total = compare(x);
        
        if( total != 0 && total < 4){
            successTotalMsg(total);
            int exist = exist(x);
            
            if(exist != 0 && exist < 4){
                successPartialMsg(exist);
            }
            
            subtractAttempts();
            
        }else if(total == 4){
            
            successTotalMsg(total);
            disableBtn();
            btnStartGame.setEnabled(true);
            result.setText("Usted ganó");
            result2.setText("");
            generateRandomLetters();
        }
    }
    
    private int exist(char[] x){
        int cont = 0;
         
        for(int i = 0; i < x.length; i++){ 
            for ( String letter : combination) {
                if (letter.equals( String.valueOf(x[i]) )) {
                    cont += 1;
                }   
            }
        }
        return cont;
    }
    
    private void successPartialMsg(int num){
       result2.setText("Aciertos parciales: " + num);
    }
    
    private void successTotalMsg(int num){
        result.setText("Aciertos totales: " + num);
    }
    
    private void disableBtn(){
        attempt.setEnabled(false);
        btnSubmit.setEnabled(false);
    }
    
    private void erroMsg(){
        if(attempts != 0){
            result.setText("Intentelo de nuevo");
            subtractAttempts();
        }else{
            result.setText("Game Over");
            btnStartGame.setEnabled(true);
            disableBtn();
        }
    }
    
    private void subtractAttempts(){
        if(attempts != 0){
            attempts -= 1;
            attemptsAvailable.setText(String.valueOf(attempts));
        }else{
            erroMsg();
        }
    }
    
    private int compare(char[] x){
        int cont = 0;
        
        for(int i = 0; i < combination.length; i++){
            if(combination[i].equals(String.valueOf(x[i]))){
                cont += 1 ;
            }
        }
        return cont;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStartGame = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        attempt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        attemptsAvailable = new javax.swing.JLabel();
        result = new javax.swing.JLabel();
        result2 = new javax.swing.JLabel();

        btnStartGame.setText("Iniciar juego");
        btnStartGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStartGameMouseClicked(evt);
            }
        });
        btnStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartGameActionPerformed(evt);
            }
        });

        btnSubmit.setText("Confirmar");
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmitMouseClicked(evt);
            }
        });

        attempt.setToolTipText("");

        jLabel1.setText("Intentos disponibles:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnStartGame)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(attemptsAvailable))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addComponent(btnSubmit))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(attempt, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(result2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStartGame)
                    .addComponent(jLabel1)
                    .addComponent(attemptsAvailable))
                .addGap(17, 17, 17)
                .addComponent(attempt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(result2, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel1.getAccessibleContext().setAccessibleName("");
        jLabel1.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartGameActionPerformed

    }//GEN-LAST:event_btnStartGameActionPerformed

    private void btnStartGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartGameMouseClicked
        btnStartGame.setEnabled(false);
        attempt.setEnabled(true);
        btnSubmit.setEnabled(true);
    }//GEN-LAST:event_btnStartGameMouseClicked

    private void btnSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseClicked
        turnIntoArray();
        
    }//GEN-LAST:event_btnSubmitMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField attempt;
    private javax.swing.JLabel attemptsAvailable;
    private javax.swing.JButton btnStartGame;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel result;
    private javax.swing.JLabel result2;
    // End of variables declaration//GEN-END:variables
}
